// source: layer1/caller/v1/session.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var layer1_caller_v1_signaling_pb = require('../../../layer1/caller/v1/signaling_pb.js');
goog.object.extend(proto, layer1_caller_v1_signaling_pb);
goog.exportSymbol('proto.v1.caller.v1.SessionInfo', null, global);
goog.exportSymbol('proto.v1.caller.v1.SessionInfo.Call_state', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.caller.v1.SessionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v1.caller.v1.SessionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.caller.v1.SessionInfo.displayName = 'proto.v1.caller.v1.SessionInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.caller.v1.SessionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.caller.v1.SessionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.caller.v1.SessionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.caller.v1.SessionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    opponentRtcState: (f = msg.getOpponentRtcState()) && layer1_caller_v1_signaling_pb.Signaling.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.caller.v1.SessionInfo}
 */
proto.v1.caller.v1.SessionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.caller.v1.SessionInfo;
  return proto.v1.caller.v1.SessionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.caller.v1.SessionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.caller.v1.SessionInfo}
 */
proto.v1.caller.v1.SessionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 2:
      var value = /** @type {!proto.v1.caller.v1.SessionInfo.Call_state} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 4:
      var value = new layer1_caller_v1_signaling_pb.Signaling;
      reader.readMessage(value,layer1_caller_v1_signaling_pb.Signaling.deserializeBinaryFromReader);
      msg.setOpponentRtcState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.caller.v1.SessionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.caller.v1.SessionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.caller.v1.SessionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.caller.v1.SessionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getOpponentRtcState();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      layer1_caller_v1_signaling_pb.Signaling.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.v1.caller.v1.SessionInfo.Call_state = {
  CALL_STATE_NONE: 0,
  CALL_STATE_WAITING: 1,
  CALL_STATE_ACTIVE: 2,
  CALL_STATE_ENDED: 3
};

/**
 * optional string session_id = 1;
 * @return {string}
 */
proto.v1.caller.v1.SessionInfo.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.caller.v1.SessionInfo} returns this
 */
proto.v1.caller.v1.SessionInfo.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Call_state state = 2;
 * @return {!proto.v1.caller.v1.SessionInfo.Call_state}
 */
proto.v1.caller.v1.SessionInfo.prototype.getState = function() {
  return /** @type {!proto.v1.caller.v1.SessionInfo.Call_state} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.v1.caller.v1.SessionInfo.Call_state} value
 * @return {!proto.v1.caller.v1.SessionInfo} returns this
 */
proto.v1.caller.v1.SessionInfo.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Signaling opponent_rtc_state = 4;
 * @return {?proto.v1.caller.v1.Signaling}
 */
proto.v1.caller.v1.SessionInfo.prototype.getOpponentRtcState = function() {
  return /** @type{?proto.v1.caller.v1.Signaling} */ (
    jspb.Message.getWrapperField(this, layer1_caller_v1_signaling_pb.Signaling, 4));
};


/**
 * @param {?proto.v1.caller.v1.Signaling|undefined} value
 * @return {!proto.v1.caller.v1.SessionInfo} returns this
*/
proto.v1.caller.v1.SessionInfo.prototype.setOpponentRtcState = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v1.caller.v1.SessionInfo} returns this
 */
proto.v1.caller.v1.SessionInfo.prototype.clearOpponentRtcState = function() {
  return this.setOpponentRtcState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.caller.v1.SessionInfo.prototype.hasOpponentRtcState = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.v1.caller.v1);
